# Dependencies
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Nattfodd
tagline:          'Aleksey Nattfodd Kuznietsov'
description:      'Yet another blog on the Internet. Personal life, software development, photography, travelling and so on.'
url:              'https://nattfodd.com'
baseurl:          '/'

author:
  name:           'Aleksey Kuznietsov'
  url:            https://twitter.com/nattf0dd

paginate:          10

excerpt:           'Read more...'
excerpt_separator: <!--more-->

# Custom vars
social:
  twitter:          https://twitter.com/nattf0dd
  facebook:         https://www.facebook.com/nattf0dd
  github:           https://github.com/nattfodd
  stackoverflow:    https://stackoverflow.com/users/7177640/nattfodd
  linkedin:         https://www.linkedin.com/in/oleksii-kuznietsov-42655487/
  telegram:         https://telegram.me/nattf0dd
  cv:               https://docs.google.com/document/d/1HOAfsZZ5_wCHcCxRnaZPuxT571eIPcjKmB1y34tMkZU
  youtube:          https://www.youtube.com/channel/UC_u_udKTu0vjncd8N3VPT-w?view_as=subscriber
